# 创建Tensor

In [1]:
import torch

### unitialized

In [11]:
print(torch.empty(2,3))
print(torch.IntTensor(1,2,3))
print(torch.FloatTensor(1,2,3))

tensor([[1.3590e+22, 1.6519e-04, 4.1725e+21],
        [8.5454e-07, 4.1469e-11, 7.1450e+31]])
tensor([[[1681403192,  959264307, 1667379297],
         [ 895836982,  775315813, 1952543859]]], dtype=torch.int32)
tensor([[[1.0682e-05, 1.0026e-11, 5.2059e+22],
         [8.5385e-07, 1.3590e+22, 1.6519e-04]]])


In [18]:
torch.Tensor(1,1,2)

tensor([[[0., 0.]]])

### set default type

In [23]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.,2.,3.]).type()

'torch.DoubleTensor'

In [26]:
a = torch.rand(3,3)
torch.rand_like(a)
torch.randint(1, 10, [3, 3])

tensor([[9, 6, 5],
        [3, 2, 2],
        [1, 6, 5]])

In [30]:
torch.logspace(0, 1, steps = 10, base = torch.e)

tensor([1.0000, 1.1175, 1.2488, 1.3956, 1.5596, 1.7429, 1.9477, 2.1766, 2.4324,
        2.7183])

In [43]:
idx = torch.randperm(10)
idx

tensor([2, 0, 5, 4, 8, 7, 3, 1, 9, 6])